### ISSUE TITLE
Problems connecting to Heroku Kafka after upgrading from v1 to v2

### ISSUE THREAD

**Issue by thorstenspringhart** [zendesk/racecar#195]
Hi,

I used racecar v1 successfully on Heroku with the Heroku Kafka Addon. Now i want to upgrade to v2 but have different problems...

My config looked like this:
 
```
  tmp_ca_file = Tempfile.new('ca_certs')
  tmp_ca_file.write(ENV.fetch('KAFKA_TRUSTED_CERT'))
  tmp_ca_file.close

  Racecar.configure do |config|
    config.brokers = ENV.fetch('KAFKA_URL')
    config.logger = Rails.logger
    config.group_id_prefix = ENV.fetch('KAFKA_PREFIX')
    config.session_timeout = 120
    config.ssl_ca_cert_file_path = tmp_ca_file.path
    config.ssl_client_cert = ENV.fetch('KAFKA_CLIENT_CERT')
    config.ssl_client_cert_key = ENV.fetch('KAFKA_CLIENT_CERT_KEY')
    config.ssl_verify_hostname = false
  end
```

and it worked fine.

After upgrading to 2.1.0 i ran into different problems

On Heroku the KAFKA_URL environment variable looks something like `kafka+ssl://ec2-xxxx.eu-west-1.compute.amazonaws.com:9096,kafka+ssl://ec2-xxxx...`

After the ugrade, the runner complains that the brokers are a string
```
=> Crashed: NoMethodError: undefined method `join' for #<String:0x00007f9fc75dafc0>
/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/racecar-2.1.0/lib/racecar/runner.rb:129:in `producer_config'
```

So i splitted the comma list myself (so that the runner can join it again ;) ), after that rdkafka complained about the protocol

`rdkafka: [thrd:app]: Broker name "kafka+ssl://xxxx.compute.amazonaws.com:9096,kafka+ssl://xxxx.comput" parse error: unsupported protocol "KAFKA+SSL"`

i removed the protocol, from the URLs (to have `ec2-xxxx.eu-west-1.compute.amazonaws.com:9096,ec2-xxxx...` )

Now there is no error  but also no log about joining the groups etc, and my consumer does not get any messages

All i got is

```
❯ bundle exec racecar DummyConsumer
=> Starting Racecar consumer DummyConsumer...
=> Detected Rails, booting application...
=> Wrooooom!
=> Ctrl-C to shutdown consumer
```

This is my config now:

```
def cert_file(name, contents)
  cert_file = Tempfile.new(name)
  cert_file << contents
  cert_file.flush
  cert_file.path
end

  Racecar.configure do |config|
    config.log_level = 'debug'
    config.brokers = ENV.fetch('KAFKA_URL').split(',')
    config.logger = Rails.logger
    config.group_id_prefix = ENV.fetch('KAFKA_PREFIX')
    config.session_timeout = 120
    config.ssl_ca_location = cert_file('ca_certs', ENV.fetch('KAFKA_TRUSTED_CERT'))
    config.ssl_certificate_location = cert_file('client_certs', ENV.fetch('KAFKA_CLIENT_CERT'))
    config.ssl_key_location = cert_file('cert_key', ENV.fetch('KAFKA_CLIENT_CERT_KEY'))
    config.ssl_verify_hostname = false
  end
```
Any ideas what could be the issue now and why there are absolute no logs? And do you plan to support heroku kafka easier like it was possible with v1?

Thanks

Thorsten

**Comment by dasch** [comment]
You probably need to do this:

```ruby
config.brokers = ENV.fetch('KAFKA_URL').split(",")
```

The comma-separated string support is only done for the `RACECAR_BROKERS` ENV var.

**Comment by dasch** [comment]
1. Are those ENV vars all standard for Heroku? I could perhaps include turn-key support for accepting that configuration, e.g. with `require "racecar/heroku"`.
2. Can you check the rdkafka-ruby docs and perhaps see if you can get things working directly with that library, just to see if the problem lies there or in Racecar's handling of config (or mapping it to rdkafka).

**Comment by alan-sapaad** [comment]
@dasch 
1. Yes those ENVs are all standard for Heroku

For me also it was working before with this configuration:

```
Racecar.configure do |config|
  config.brokers = KAFKA_URL.to_s.split(',')
  config.ssl_ca_cert = ENV['KAFKA_TRUSTED_CERT']
  config.ssl_client_cert = ENV['KAFKA_CLIENT_CERT']
  config.ssl_client_cert_key = ENV['KAFKA_CLIENT_CERT_KEY']
  config.ssl_verify_hostname = false

  config.group_id = ENV['KAFKA_PREFIX'] + 'sample'
  config.group_id_prefix = ENV['KAFKA_PREFIX']
end
```

**Comment by dasch** [comment]
Did anyone get a working configuration? If so, can you share it here?

**Comment by alan-sapaad** [comment]
I ended up downgrading racecar to v1 @dasch

**Comment by edgurgel** [comment]
@dasch @alan-sapaad  I ended up doing something like this:

```ruby
Racecar.configure do |config|
  ca_cert = ENV['KAFKA_TRUSTED_CERT']
  client_cert = ENV['KAFKA_CLIENT_CERT']
  client_cert_key = ENV['KAFKA_CLIENT_CERT_KEY']

  tmp_file_path = lambda do |data|
    filename = Rails.root.join('tmp', "#{SecureRandom.uuid}.pem")
    file = File.new(filename, "w")
    file.close

    file.path
  end

  if ca_cert.present? && client_cert.present? && client_cert_key.present?
    config.security_protocol = :ssl
    config.ssl_ca_location = tmp_file_path.call(ca_cert)
    config.ssl_certificate_location = tmp_file_path.call(client_cert)
    config.ssl_key_location = tmp_file_path.call(client_cert_key)
  end

  config.brokers = ENV['KAFKA_URL'].gsub('kafka+ssl://', '')
end

```


the prefix I handled myself when providing topic and consumer group names by prepending `ENV['KAFKA_PREFIX']`

**Comment by alan-sapaad** [comment]
@edgurgel Thank you. Let me try this.

**Comment by reggieb** [comment]
I don't think @edgurgel solution is quite right. The `tmp_file_path` definition doesn't actually write `data` to the new file. 

This worked for me:
```ruby
Racecar.configure do |config|
  ca_cert = ENV['KAFKA_TRUSTED_CERT']
  client_cert = ENV['KAFKA_CLIENT_CERT']
  client_cert_key = ENV['KAFKA_CLIENT_CERT_KEY']

  tmp_file_path = lambda do |data|
    filename = Rails.root.join("tmp", "#{SecureRandom.uuid}.pem")
    File.write(filename, data)
    filename
  end

  if ca_cert.present? && client_cert.present? && client_cert_key.present?
    config.security_protocol = :ssl
    config.ssl_ca_location = tmp_file_path.call(ca_cert)
    config.ssl_certificate_location = tmp_file_path.call(client_cert)
    config.ssl_key_location = tmp_file_path.call(client_cert_key)
  end

  config.brokers = ENV['KAFKA_URL'].gsub('kafka+ssl://', '').split(',')
end
```

**Comment by edgurgel** [comment]
Oops you are right! While copying the solution I ended up removing this somehow! My bad! Nice catch

**Comment by dasch** [comment]
Would someone here be willing to create a PR that fully automates setting up Racecar on Heroku? Basically, add a file in `lib/racecar/heroku.rb` that does the above – I assume it's the same for all Heroku apps. Then add a section to the README stating that Heroku users can just `require "racecar/heroku"`.

**Comment by dasch** [comment]
And please test it out, also.

**Comment by alan-sapaad** [comment]
@dasch I've created a PR just for this. https://github.com/zendesk/racecar/pull/248
Please take a look
